---@class lc.Interpreter.Submission
---@field interpret_id string
---@field test_case string

---@alias submission lc.Interpreter.Submission

---@alias interpret.state
---| "PENDING"
---| "STARTED"
---| "SUCCESS"
---| "FAILURE"

---@class lc.Interpreter.Response
---@field status_code integer
---@field lang string
---@field run_success boolean
---@field compile_error string
---@field full_compile_error string
---@field full_runtime_error string
---@field status_runtime string
---@field memory integer
---@field code_answer string[]
---@field expected_code_answer string[]
---@field code_output table
---@field std_output_list table
---@field task_finish_time integer
---@field task_name string
---@field correct_answer boolean
---@field total_correct any
---@field total_testcases any
---@field runtime_percentile any
---@field status_memory string
---@field memory_percentile any
---@field pretty_lang string
---@field submission_id string
---@field status_msg string
---@field state interpret.state
---@field case_idx integer

--------------------------------------------
--- Runtime Error | 15
--------------------------------------------
---@class lc.Interpreter.Response.runtime_error
---@field status_code number
---@field lang string
---@field run_success boolean
---@field code_answer table
---@field code_output table
---@field runtime_error string
---@field full_runtime_error string
---@field invalid_testcase boolean
---@field case_idx number
---@field param_idx number
---@field task_finish_time number
---@field task_name string
---@field total_correct number | nil
---@field total_testcases number | nil
---@field status_runtime string
---@field runtime_percentile number | nil
---@field status_memory string
---@field memory_percentile number | nil
---@field pretty_lang string
---@field submission_id string
---@field status_msg string
---@field state string

---@alias runtime_error lc.Interpreter.Response.runtime_error

--------------------------------------------
--- Runtime | 10
--------------------------------------------
---@class lc.Interpreter.Response.runtime
---@field status_code number
---@field lang string
---@field run_success boolean
---@field status_runtime string
---@field memory number
---@field display_runtime string
---@field code_answer table
---@field code_output table
---@field std_output_list table
---@field elapsed_time number
---@field task_finish_time number
---@field task_name string
---@field expected_status_code number
---@field expected_lang string
---@field expected_run_success boolean
---@field expected_status_runtime string
---@field expected_memory number
---@field expected_code_answer table
---@field expected_code_output table
---@field expected_std_output_list table
---@field expected_elapsed_time number
---@field expected_task_finish_time number
---@field expected_task_name string
---@field correct_answer boolean
---@field compare_result string
---@field total_correct number
---@field total_testcases number
---@field runtime_percentile number | nil
---@field status_memory string
---@field memory_percentile number | nil
---@field pretty_lang string
---@field submission_id string
---@field status_msg string
---@field state string

---@alias runtime lc.Interpreter.Response.runtime

--------------------------------------------
--- Compile Error | 20
--------------------------------------------
---@class lc.Interpreter.Response.compile_error
---@field status_code number
---@field lang string
---@field run_success boolean
---@field compile_error string
---@field full_compile_error string
---@field status_runtime string
---@field memory number
---@field code_answer table
---@field code_output table
---@field std_output_list table
---@field task_finish_time number
---@field task_name string
---@field total_correct number | nil
---@field total_testcases number | nil
---@field runtime_percentile number | nil
---@field status_memory string
---@field memory_percentile number | nil
---@field pretty_lang string
---@field submission_id string
---@field status_msg string
---@field state string

---@alias compile_error lc.Interpreter.Response.compile_error

--------------------------------------------
--- Time Limit Exceeded | 13, 14
--------------------------------------------
---@class lc.Interpreter.Response.limit.exceeded
---@field code_answer table
---@field code_output table
---@field elapsed_time integer
---@field lang string
---@field memory number
---@field memory_percentile number | nil
---@field pretty_lang string
---@field run_success boolean
---@field runtime_percentile number | nil
---@field state string
---@field status_code number
---@field status_memory string
---@field status_msg string
---@field status_runtime string
---@field std_output_list table
---@field submission_id string
---@field task_finish_time number
---@field task_name string
---@field total_correct number | nil
---@field total_testcases number | nil

---@alias limit_exceeded_error lc.Interpreter.Response.limit.exceeded

--------------------------------------------
--- Time Limit Exceeded | 13, 14
--------------------------------------------
---@class lc.Interpreter.Response.internal.error
---@field status_code integer
---@field status_msg string
---@field state interpret.state

---@alias internal_error lc.Interpreter.Response.internal.error

--------------------------------------------
--- Interpreter responses
--------------------------------------------
---@alias interpreter_response
---| runtime
---| runtime_error
---| compile_error
---| limit_exceeded_error
---| internal_error

--------------------------------------------
--- Code snipppet
--------------------------------------------
---@class lc.QuestionCodeSnippet
---@field lang string
---@field lang_slug string
---@field code string

---@alias code_snippet lc.QuestionCodeSnippet

--------------------------------------------
--- Metadata Param
--------------------------------------------
---@class lc.QuestionResponse.metadata.param
---@field name string
---@field type string

---@alias metadata_param lc.QuestionResponse.metadata.param

--------------------------------------------
--- Metadata Return
--------------------------------------------
---@class lc.QuestionResponse.metadata.return
---@field type string
---@field size integer

---@alias metadata_return lc.QuestionResponse.metadata.return

--------------------------------------------
--- Metadata
--------------------------------------------
---@class lc.QuestionResponse.metadata
---@field manual boolean
---@field name string
---@field params metadata_param[]
---@field return metadata_return

---@alias metadata lc.QuestionResponse.metadata

--------------------------------------------
--- Question Response
--------------------------------------------
---@class lc.QuestionResponse
---@field id integer
---@field frontend_id integer
---@field title string
---@field title_slug string
---@field id_paid_only boolean
---@field difficulty string
---@field likes integer
---@field dislikes integer
---@field category_title string
---@field content string
---@field mysql_schemas string[]
---@field data_schemas string[]
---@field code_snippets code_snippet[]
---@field testcase_list string[]
---@field meta_data metadata

---@alias question_response lc.QuestionResponse
