---@class lc.Imports
local imports = {}

imports["python3"] = {
    "from string import *",
    "from re import *",
    "from datetime import *",
    "from collections import *",
    "from heapq import *",
    "from bisect import *",
    "from copy import *",
    "from math import *",
    "from random import *",
    "from statistics import *",
    "from itertools import *",
    "from functools import *",
    "from operator import *",
    "from io import *",
    "from sys import *",
    "from json import *",
    "from builtins import *",
    "import string",
    "import re",
    "import datetime",
    "import collections",
    "import heapq",
    "import bisect",
    "import copy",
    "import math",
    "import random",
    "import statistics",
    "import itertools",
    "import functools",
    "import operator",
    "import io",
    "import sys",
    "import json",
    "from typing import *",
}

imports["python"] = {
    "from bisect import *",
    "from collections import *",
    "from copy import *",
    "from datetime import *",
    "from heapq import *",
    "from math import *",
    "from re import *",
    "from string import *",
    "from random import *",
    "from itertools import *",
    "from functools import *",
    "from operator import *",
    "import string",
    "import re",
    "import datetime",
    "import collections",
    "import heapq",
    "import bisect",
    "import copy",
    "import math",
    "import random",
    "import itertools",
    "import functools",
    "import operator",
}

imports["java"] = {
    "import java.util.*;",
    "import java.math.*;",
}

return imports
