---@class lc.language
---@field lang string
---@field slug string
---@field icon string
---@field color string
---@field hl? string
---@field comment string
---@field ft string
---@field alt? string

---@type lc.language[]
return {
    {
        lang = "C++",
        slug = "cpp",
        icon = "",
        color = "#00599C",
        ft = "cpp",
        comment = "//",
    },
    {
        lang = "Java",
        slug = "java",
        icon = "",
        color = "#E76F00",
        ft = "java",
        comment = "//",
    },
    {
        lang = "Python",
        slug = "python",
        icon = "",
        color = "#306998",
        ft = "py",
        comment = "#",
        alt = "python2",
    },
    {
        lang = "Python3",
        slug = "python3",
        icon = "",
        color = "#306998",
        ft = "py",
        comment = "#",
    },
    {
        lang = "C",
        slug = "c",
        icon = "",
        color = "#555555",
        ft = "c",
        comment = "//",
    },
    {
        lang = "C#",
        slug = "csharp",
        icon = "󰌛",
        color = "#68217A",
        ft = "cs",
        comment = "//",
    },
    {
        lang = "JavaScript",
        slug = "javascript",
        icon = "",
        color = "#F0DB4F",
        ft = "js",
        comment = "//",
    },
    {
        lang = "TypeScript",
        slug = "typescript",
        icon = "",
        color = "#3178C6",
        ft = "ts",
        comment = "//",
    },
    {
        lang = "PHP",
        slug = "php",
        icon = "",
        color = "#777BB4",
        ft = "php",
        comment = "//",
    },
    {
        lang = "Swift",
        slug = "swift",
        icon = "",
        color = "#FFAC45",
        ft = "swift",
        comment = "//",
    },
    {
        lang = "Kotlin",
        slug = "kotlin",
        icon = "",
        color = "#7F52FF",
        ft = "kt",
        comment = "//",
    },
    {
        lang = "Dart",
        slug = "dart",
        icon = "",
        color = "#1057A7",
        ft = "dart",
        comment = "//",
    },
    {
        lang = "Go",
        slug = "golang",
        icon = "",
        color = "#00ADD8",
        ft = "go",
        comment = "//",
    },
    {
        lang = "Ruby",
        slug = "ruby",
        icon = "",
        color = "#CC342D",
        ft = "rb",
        comment = "#",
    },
    {
        lang = "Scala",
        slug = "scala",
        icon = "",
        color = "#DC322F",
        ft = "scala",
        comment = "//",
    },
    {
        lang = "Rust",
        slug = "rust",
        icon = "",
        color = "#DEA584",
        ft = "rs",
        comment = "//",
    },
    {
        lang = "Racket",
        slug = "racket",
        icon = "󰰟",
        color = "#22228F",
        ft = "rkt",
        comment = ";;",
    },
    {
        lang = "Erlang",
        slug = "erlang",
        icon = "",
        color = "#A90533",
        ft = "erl",
        comment = "%",
    },
    {
        lang = "Elixir",
        slug = "elixir",
        icon = "",
        color = "#6E4A7E",
        ft = "ex",
        comment = "#",
    },
    {
        lang = "Bash",
        slug = "bash",
        icon = "󱆃",
        color = "#000000",
        ft = "sh",
        comment = "#",
    },
}
