---@class lc.language
---@field lang string
---@field slug string
---@field icon string
---@field color string
---@field short string
---@field hl? string
---@field comment string
---@field sql boolean|nil
---@field ft string

---@type lc.language[]
return {
    {
        lang = "C++",
        slug = "cpp",
        icon = "",
        color = "#00599C",
        short = "cpp",
        ft = "cpp",
        comment = "//",
    },
    {
        lang = "Java",
        slug = "java",
        icon = "",
        color = "#E76F00",
        short = "java",
        ft = "java",
        comment = "//",
    },
    {
        lang = "Python",
        slug = "python",
        icon = "",
        color = "#306998",
        short = "pythn",
        ft = "py",
        comment = "#",
    },
    {
        lang = "Python3",
        slug = "python3",
        icon = "",
        color = "#306998",
        short = "pyth3",
        ft = "py",
        comment = "#",
    },
    {
        lang = "C",
        slug = "c",
        icon = "",
        color = "#555555",
        short = "clang",
        ft = "c",
        comment = "//",
    },
    {
        lang = "C#",
        slug = "csharp",
        icon = "󰌛",
        color = "#68217A",
        short = "cshrp",
        ft = "cs",
        comment = "//",
    },
    {
        lang = "JavaScript",
        slug = "javascript",
        icon = "",
        color = "#F0DB4F",
        short = "js",
        ft = "js",
        comment = "//",
    },
    {
        lang = "TypeScript",
        slug = "typescript",
        icon = "",
        color = "#3178C6",
        short = "ts",
        ft = "ts",
        comment = "//",
    },
    {
        lang = "PHP",
        slug = "php",
        icon = "",
        color = "#777BB4",
        short = "php",
        ft = "php",
        comment = "//",
    },
    {
        lang = "Swift",
        slug = "swift",
        icon = "",
        color = "#FFAC45",
        short = "swift",
        ft = "swift",
        comment = "//",
    },
    {
        lang = "Kotlin",
        slug = "kotlin",
        icon = "",
        color = "#7F52FF",
        short = "ktlin",
        ft = "kt",
        comment = "//",
    },
    {
        lang = "Dart",
        slug = "dart",
        icon = "",
        color = "#1057A7",
        short = "dart",
        ft = "dart",
        comment = "//",
    },
    {
        lang = "Go",
        slug = "golang",
        icon = "",
        color = "#00ADD8",
        short = "golng",
        ft = "go",
        comment = "//",
    },
    {
        lang = "Ruby",
        slug = "ruby",
        icon = "",
        color = "#CC342D",
        short = "ruby",
        ft = "rb",
        comment = "#",
    },
    {
        lang = "Scala",
        slug = "scala",
        icon = "",
        color = "#DC322F",
        short = "scala",
        ft = "scala",
        comment = "//",
    },
    {
        lang = "Rust",
        slug = "rust",
        icon = "",
        color = "#DEA584",
        short = "rust",
        ft = "rs",
        comment = "//",
    },
    {
        lang = "Racket",
        slug = "racket",
        icon = "󰰟",
        color = "#22228F",
        short = "rcket",
        ft = "rkt",
        comment = ";;",
    },
    {
        lang = "Erlang",
        slug = "erlang",
        icon = "",
        color = "#A90533",
        short = "erlng",
        ft = "erl",
        comment = "%",
    },
    {
        lang = "Elixir",
        slug = "elixir",
        icon = "",
        color = "#6E4A7E",
        short = "elixr",
        ft = "ex",
        comment = "#",
    },
    {
        lang = "Bash",
        slug = "bash",
        icon = "󱆃",
        color = "#000000",
        short = "bash",
        ft = "sh",
        comment = "#",
    },
    -- {
    --     lang = "HTML",
    --     slug = "html",
    --     icon = "",
    --     color = "#E44D26",
    --     short = "html",
    --     ft = "html",
    --     comment = "<!--",
    -- },
    {
        lang = "Python ML",
        slug = "pythonml",
        icon = "",
        color = "#306998",
        short = "pyml",
        ft = "py",
        comment = "#",
    },
    {
        lang = "React",
        slug = "react",
        icon = "⚛",
        color = "#61DAFB",
        short = "ract",
        ft = "jsx",
        comment = "//",
    },
    {
        lang = "Vanilla JS",
        slug = "vanillajs",
        icon = "",
        color = "#F7DF1E",
        short = "vjs",
        ft = "js",
        comment = "//",
    },
}
